### ISSUE TITLE
Make Alexa Skill ID configurable

### ISSUE THREAD

**Issue by SwathiVarkala** [akhil-ghatiki/foreCastAlexSkillBackend#1]
Remove hardcoded Alexa Skill Id from code and make it configurable through properties yml file
https://github.com/akhil-ghatiki/foreCastAlexSkillBackend/blob/master/src/main/java/com/thoughtworks/forecastAlexaSkillBackend/servlet/AlexaServlet.java#L38

**Comment by SwathiVarkala** [comment]
Code Changes for this 
https://github.com/akhil-ghatiki/foreCastAlexSkillBackend/pull/4

**Comment by akhil-ghatiki** [comment]
approved and merged this PR. closing the issue.
