### ISSUE TITLE
Process the predicted json file for the launch intent handler

### ISSUE THREAD

**Issue by akhil-ghatiki** [akhil-ghatiki/foreCastAlexSkillBackend#3]
**Details:**

1. Come up with a consumer contract for the json file.
2. Have a dummy file with values for now.
3. Process this file and enrich the speech output with those values in the launch intent.

**Expectation:**
When the user starts the skill with the launch intent, the backend should process the file and speak out the enriched string.

**Comment by SwathiVarkala** [comment]
Dummy file is read and alexa takes orders according to that.
Improvisation : json per user to be handled in https://github.com/akhil-ghatiki/foreCastAlexSkillBackend/issues/22
