### ISSUE TITLE
Read Shopping list suggestion JSON data and show it to the user

### ISSUE THREAD

**Issue by bsneha90** [akhil-ghatiki/foreCastAlexSkillBackend#5]

**Comment by bsneha90** [comment]
Custom intents required:
![image](https://user-images.githubusercontent.com/19551165/79071915-d3301280-7cfb-11ea-8146-072ca0b2193f.png)

Inbuilt Intent: 
![image](https://user-images.githubusercontent.com/19551165/79071922-e0e59800-7cfb-11ea-9ca4-74f0e4a188ea.png)

Utterance:
![image](https://user-images.githubusercontent.com/19551165/79071936-f6f35880-7cfb-11ea-81ba-93f8389b26a5.png)

![image](https://user-images.githubusercontent.com/19551165/79071946-0377b100-7cfc-11ea-8072-739d3cbc67e0.png)

**Comment by akhil-ghatiki** [comment]
Does this issue refer to creating the intent in dev console of alexa ?

**Comment by bsneha90** [comment]
PR merged.
